// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozbdktxfiopniulmllkg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96YmRrdHhmaW9wbml1bG1sbGtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MzI0MTcsImV4cCI6MjA2NTIwODQxN30.JSeYp_fHzjo9dkK1EmAmHyqMLgk0VNXfu4jMk3QdbY8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);